version: '3.4'

services:
  amudario:
    image: amudario
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: "redis:alpine"
    command: redis-server
    container_name: redis
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A amudario worker -l info
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A amudario worker --beat
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - redis

    